---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: simple-app
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: jszroberto/helloworld
